### ISSUE TITLE
error run tool 

### ISSUE THREAD

**Issue by a88xss** [0xTeles/jsleak#22]
Good day to all the team that supports JSleak, I would like your support. I have this error when executing the tool both on a vps and on my local computer, any recommendations?

![Captura desde 2022-06-11 21-13-33](https://user-images.githubusercontent.com/36142867/173211481-fe6f2854-6802-4e2d-87c9-3b8ca7f4c8aa.png)

**Comment by 0xTeles** [comment]
Hello @a88xss, apparently your regex is missing the closing parenthesis

**Comment by a88xss** [comment]
Hello 0xteles you were right I omitted that part and it was that misformed line of the expression thank you very much for your guidance, a hug from Colombia  :)

**Comment by 0xTeles** [comment]
No worries. Thanks for using tool and hugs from Brazil :)
